### ISSUE TITLE
Mushrooms grow to fast and outside the forest

### ISSUE THREAD

**Issue by MarkuBu** [NPXcoot/nsspf#1]
The mushrooms grow extremely fast and outside the forest. I assume that they only grow near forests

![bildschirmfoto vom 2017-01-05 13-36-55](https://cloud.githubusercontent.com/assets/16163058/21680774/1f1c6c50-d34c-11e6-8feb-33758b66d118.png)

**Comment by NPXcoot** [comment]
Solved (I hope...)! Fungi dies when mycelium grows too much.
And mushrooms and fungusdirt are removed after 5 minutes.
