### ISSUE TITLE
Armillaria mellea can be placed everywhere

### ISSUE THREAD

**Issue by MarkuBu** [NPXcoot/nsspf#2]
This mushroom (and maybe other tree attached mushrooms) can be placed on the ground and floats in the air. Should be checked if there is a tree

![bildschirmfoto vom 2017-01-05 13-40-11](https://cloud.githubusercontent.com/assets/16163058/21680869/a1b4c7f2-d34c-11e6-8a6f-6fd5b743a950.png)

**Comment by NPXcoot** [comment]
Mushrooms can't be placed at all.
